### ISSUE TITLE
参加・離脱処理のエラー

### ISSUE THREAD

**Issue by supleiades** [mo9mo9study/discord.CodeWarehouse#46]
```node
---> 参加時
---> 参加者: yuuty
(node:23733) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'code' of undefined
    at /home/centos/repos/discord.CodeWarehouse/node/join_leave_log.js:42:48
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:23733) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
---> 招待作成
---> 招待作成
---> 招待作成
---> 参加時
---> 参加者: ゆうち
(node:23733) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'code' of undefined
    at /home/centos/repos/discord.CodeWarehouse/node/join_leave_log.js:42:48
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:23733) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
```

**Comment by su-pleiades** [comment]
この問題、使用回数１回の時に発生しているかも

**Comment by su-pleiades** [comment]
自分で抜けた時の処理
```py
[('__abstractmethods__', frozenset()), ('__class__', <class 'discord.member.Member'>), ('__delattr__', <method-wrapper '__delattr__' of Member object at 0x7faaeb5ef6d0>), ('__dir__', <built-in method __dir__ of Member object at 0x7faaeb5ef6d0>), ('__doc__', "Represents a Discord member to a :class:`Guild`.\n\n    This implements a lot of the functionality of :class:`User`.\n\n    .. container:: operations\n\n        .. describe:: x == y\n\n            Checks if two members are equal.\n            Note that this works with :class:`User` instances too.\n\n        .. describe:: x != y\n\n            Checks if two members are not equal.\n            Note that this works with :class:`User` instances too.\n\n        .. describe:: hash(x)\n\n            Returns the member's hash.\n\n        .. describe:: str(x)\n\n            Returns the member's name with the discriminator.\n\n    Attributes\n    ----------\n    joined_at: Optional[:class:`datetime.datetime`]\n        A datetime object that specifies the date and time in UTC that the member joined the guild.\n        If the member left and rejoined the guild, this will be the latest date. In certain cases, this can be ``None``.\n    activities: Tuple[Union[:class:`BaseActivity`, :class:`Spotify`]]\n        The activities that the user is currently doing.\n    guild: :class:`Guild`\n        The guild that the member belongs to.\n    nick: Optional[:class:`str`]\n        The guild specific nickname of the user.\n    premium_since: Optional[:class:`datetime.datetime`]\n        A datetime object that specifies the date and time in UTC when the member used their\n        Nitro boost on the guild, if available. This could be ``None``.\n    "), ('__eq__', <bound method Member.__eq__ of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('__format__', <built-in method __format__ of Member object at 0x7faaeb5ef6d0>), ('__ge__', <method-wrapper '__ge__' of Member object at 0x7faaeb5ef6d0>), ('__getattribute__', <method-wrapper '__getattribute__' of Member object at 0x7faaeb5ef6d0>), ('__gt__', <method-wrapper '__gt__' of Member object at 0x7faaeb5ef6d0>), ('__hash__', <bound method Member.__hash__ of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('__init__', <bound method Member.__init__ of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('__init_subclass__', <built-in method __init_subclass__ of ABCMeta object at 0xeef150>), ('__le__', <method-wrapper '__le__' of Member object at 0x7faaeb5ef6d0>), ('__lt__', <method-wrapper '__lt__' of Member object at 0x7faaeb5ef6d0>), ('__module__', 'discord.member'), ('__ne__', <bound method Member.__ne__ of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('__new__', <built-in method __new__ of type object at 0x921120>), ('__reduce__', <built-in method __reduce__ of Member object at 0x7faaeb5ef6d0>), ('__reduce_ex__', <built-in method __reduce_ex__ of Member object at 0x7faaeb5ef6d0>), ('__repr__', <bound method Member.__repr__ of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('__setattr__', <method-wrapper '__setattr__' of Member object at 0x7faaeb5ef6d0>), ('__sizeof__', <built-in method __sizeof__ of Member object at 0x7faaeb5ef6d0>), ('__slots__', ('_roles', 'joined_at', 'premium_since', '_client_status', 'activities', 'guild', 'nick', '_user', '_state')), ('__str__', <bound method Member.__str__ of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('__subclasshook__', <bound method User.__subclasshook__ of <class 'discord.member.Member'>>), ('_abc_impl', <_abc_data object at 0x7faaec3cf660>), ('_client_status', {'web': 'online', None: 'online'}), ('_copy', <bound method Member._copy of <class 'discord.member.Member'>>), ('_from_message', <bound method Member._from_message of <class 'discord.member.Member'>>), ('_from_presence_update', <bound method Member._from_presence_update of <class 'discord.member.Member'>>), ('_get_channel', <bound method Member._get_channel of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('_presence_update', <bound method Member._presence_update of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('_roles', SnowflakeList('Q', [801977570470920233])), ('_state', <discord.state.ConnectionState object at 0x7faaec066640>), ('_try_upgrade', <bound method Member._try_upgrade of <class 'discord.member.Member'>>), ('_update', <bound method Member._update of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('_update_from_message', <bound method Member._update_from_message of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('_update_inner_user', <bound method Member._update_inner_user of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('_update_roles', <bound method Member._update_roles of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('_user', <User id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False>), ('activities', ()), ('activity', None), ('add_roles', <bound method Member.add_roles of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('avatar', 'e8f2c3002dfb66c40e7db1b0a3cd227a'), ('avatar_url', <Asset url='/avatars/186844273029677056/e8f2c3002dfb66c40e7db1b0a3cd227a.webp?size=1024'>), ('avatar_url_as', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('ban', <bound method Member.ban of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('block', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('bot', False), ('color', <Colour value=0>), ('colour', <Colour value=0>), ('create_dm', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('created_at', datetime.datetime(2016, 5, 30, 14, 12, 26, 89000)), ('default_avatar', <DefaultAvatar.red: 4>), ('default_avatar_url', <Asset url='/embed/avatars/4.png'>), ('desktop_status', <Status.offline: 'offline'>), ('discriminator', '5669'), ('display_name', 'KeiitiChan'), ('dm_channel', None), ('edit', <bound method Member.edit of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('fetch_message', <bound method Messageable.fetch_message of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('guild', <Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>), ('guild_permissions', <Permissions value=104193601>), ('history', <bound method Messageable.history of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('id', 186844273029677056), ('is_avatar_animated', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('is_blocked', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('is_friend', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('is_on_mobile', <bound method Member.is_on_mobile of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('joined_at', datetime.datetime(2021, 1, 26, 14, 3, 42, 341382)), ('kick', <bound method Member.kick of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('mention', '<@186844273029677056>'), ('mentioned_in', <bound method Member.mentioned_in of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('mobile_status', <Status.offline: 'offline'>), ('move_to', <bound method Member.move_to of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('mutual_friends', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('name', 'KeiitiChan'), ('nick', None), ('permissions_in', <bound method Member.permissions_in of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('pins', <bound method Messageable.pins of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('premium_since', None), ('profile', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('public_flags', <PublicUserFlags value=0>), ('raw_status', 'online'), ('relationship', None), ('remove_friend', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('remove_roles', <bound method Member.remove_roles of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('roles', [<Role id=603582455756095488 name='@everyone'>, <Role id=801977570470920233 name='everyone-bot'>]), ('send', <bound method Messageable.send of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('send_friend_request', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('status', <Status.online: 'online'>), ('system', False), ('top_role', <Role id=801977570470920233 name='everyone-bot'>), ('trigger_typing', <bound method Messageable.trigger_typing of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('typing', <bound method Messageable.typing of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('unban', <bound method Member.unban of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('unblock', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('voice', None), ('web_status', <Status.online: 'online'>)]
```

**Comment by su-pleiades** [comment]
# 追放された時

[('__abstractmethods__', frozenset()), ('__class__', <class 'discord.member.Member'>), ('__delattr__', <method-wrapper '__delattr__' of Member object at 0x7faaea9a9200>), ('__dir__', <built-in method __dir__ of Member object at 0x7faaea9a9200>), ('__doc__', "Represents a Discord member to a :class:`Guild`.\n\n    This implements a lot of the functionality of :class:`User`.\n\n    .. container:: operations\n\n        .. describe:: x == y\n\n            Checks if two members are equal.\n            Note that this works with :class:`User` instances too.\n\n        .. describe:: x != y\n\n            Checks if two members are not equal.\n            Note that this works with :class:`User` instances too.\n\n        .. describe:: hash(x)\n\n            Returns the member's hash.\n\n        .. describe:: str(x)\n\n            Returns the member's name with the discriminator.\n\n    Attributes\n    ----------\n    joined_at: Optional[:class:`datetime.datetime`]\n        A datetime object that specifies the date and time in UTC that the member joined the guild.\n        If the member left and rejoined the guild, this will be the latest date. In certain cases, this can be ``None``.\n    activities: Tuple[Union[:class:`BaseActivity`, :class:`Spotify`]]\n        The activities that the user is currently doing.\n    guild: :class:`Guild`\n        The guild that the member belongs to.\n    nick: Optional[:class:`str`]\n        The guild specific nickname of the user.\n    premium_since: Optional[:class:`datetime.datetime`]\n        A datetime object that specifies the date and time in UTC when the member used their\n        Nitro boost on the guild, if available. This could be ``None``.\n    "), ('__eq__', <bound method Member.__eq__ of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('__format__', <built-in method __format__ of Member object at 0x7faaea9a9200>), ('__ge__', <method-wrapper '__ge__' of Member object at 0x7faaea9a9200>), ('__getattribute__', <method-wrapper '__getattribute__' of Member object at 0x7faaea9a9200>), ('__gt__', <method-wrapper '__gt__' of Member object at 0x7faaea9a9200>), ('__hash__', <bound method Member.__hash__ of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('__init__', <bound method Member.__init__ of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('__init_subclass__', <built-in method __init_subclass__ of ABCMeta object at 0xeef150>), ('__le__', <method-wrapper '__le__' of Member object at 0x7faaea9a9200>), ('__lt__', <method-wrapper '__lt__' of Member object at 0x7faaea9a9200>), ('__module__', 'discord.member'), ('__ne__', <bound method Member.__ne__ of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('__new__', <built-in method __new__ of type object at 0x921120>), ('__reduce__', <built-in method __reduce__ of Member object at 0x7faaea9a9200>), ('__reduce_ex__', <built-in method __reduce_ex__ of Member object at 0x7faaea9a9200>), ('__repr__', <bound method Member.__repr__ of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('__setattr__', <method-wrapper '__setattr__' of Member object at 0x7faaea9a9200>), ('__sizeof__', <built-in method __sizeof__ of Member object at 0x7faaea9a9200>), ('__slots__', ('_roles', 'joined_at', 'premium_since', '_client_status', 'activities', 'guild', 'nick', '_user', '_state')), ('__str__', <bound method Member.__str__ of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('__subclasshook__', <bound method User.__subclasshook__ of <class 'discord.member.Member'>>), ('_abc_impl', <_abc_data object at 0x7faaec3cf660>), ('_client_status', {'web': 'online', None: 'online'}), ('_copy', <bound method Member._copy of <class 'discord.member.Member'>>), ('_from_message', <bound method Member._from_message of <class 'discord.member.Member'>>), ('_from_presence_update', <bound method Member._from_presence_update of <class 'discord.member.Member'>>), ('_get_channel', <bound method Member._get_channel of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('_presence_update', <bound method Member._presence_update of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('_roles', SnowflakeList('Q', [801977570470920233])), ('_state', <discord.state.ConnectionState object at 0x7faaec066640>), ('_try_upgrade', <bound method Member._try_upgrade of <class 'discord.member.Member'>>), ('_update', <bound method Member._update of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('_update_from_message', <bound method Member._update_from_message of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('_update_inner_user', <bound method Member._update_inner_user of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('_update_roles', <bound method Member._update_roles of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('_user', <User id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False>), ('activities', ()), ('activity', None), ('add_roles', <bound method Member.add_roles of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('avatar', 'e8f2c3002dfb66c40e7db1b0a3cd227a'), ('avatar_url', <Asset url='/avatars/186844273029677056/e8f2c3002dfb66c40e7db1b0a3cd227a.webp?size=1024'>), ('avatar_url_as', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('ban', <bound method Member.ban of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('block', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('bot', False), ('color', <Colour value=0>), ('colour', <Colour value=0>), ('create_dm', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('created_at', datetime.datetime(2016, 5, 30, 14, 12, 26, 89000)), ('default_avatar', <DefaultAvatar.red: 4>), ('default_avatar_url', <Asset url='/embed/avatars/4.png'>), ('desktop_status', <Status.offline: 'offline'>), ('discriminator', '5669'), ('display_name', 'KeiitiChan'), ('dm_channel', None), ('edit', <bound method Member.edit of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('fetch_message', <bound method Messageable.fetch_message of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('guild', <Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>), ('guild_permissions', <Permissions value=104193601>), ('history', <bound method Messageable.history of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('id', 186844273029677056), ('is_avatar_animated', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('is_blocked', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('is_friend', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('is_on_mobile', <bound method Member.is_on_mobile of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('joined_at', datetime.datetime(2021, 1, 26, 14, 4, 37, 706445)), ('kick', <bound method Member.kick of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('mention', '<@186844273029677056>'), ('mentioned_in', <bound method Member.mentioned_in of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('mobile_status', <Status.offline: 'offline'>), ('move_to', <bound method Member.move_to of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('mutual_friends', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('name', 'KeiitiChan'), ('nick', None), ('permissions_in', <bound method Member.permissions_in of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('pins', <bound method Messageable.pins of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('premium_since', None), ('profile', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('public_flags', <PublicUserFlags value=0>), ('raw_status', 'online'), ('relationship', None), ('remove_friend', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('remove_roles', <bound method Member.remove_roles of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('roles', [<Role id=603582455756095488 name='@everyone'>, <Role id=801977570470920233 name='everyone-bot'>]), ('send', <bound method Messageable.send of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('send_friend_request', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('status', <Status.online: 'online'>), ('system', False), ('top_role', <Role id=801977570470920233 name='everyone-bot'>), ('trigger_typing', <bound method Messageable.trigger_typing of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('typing', <bound method Messageable.typing of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('unban', <bound method Member.unban of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('unblock', <bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=186844273029677056 name='KeiitiChan' discriminator='5669' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=105>>>), ('voice', None), ('web_status', <Status.online: 'online'>)]

**Comment by supleiades** [comment]
解決したためクローズ
