### ISSUE TITLE
メンバー整理自動化

### ISSUE THREAD

**Issue by su-pleiades** [mo9mo9study/discord.CodeWarehouse#55]
# 目的
- 現在手動で対応している項目を自動化

# 作業項目
1. 対象者に整理時のテンプレート文章をDMで送信
2. メンバーのtimesを削除
3. メンバーをキック

# 処理について
- トリガーはコマンド形式で作ってみる？
  - 一旦何をトリガーで処理が開始するか決まってない
  - おいおいは定期処理とDBを活用して自動化したいが、今は処理の確認とコマンドでもよいかも。
- 誤って削除するのは問題なので
  - 一旦削除メンバーの一覧を出力して、それをSuが確認してからスタンプでリアクションすると処理が流れるとか。

**Comment by iceE-1591** [comment]
今日作ってプルリクします

**Comment by iceE-1591** [comment]
## 対象者を追加するコマンド
- ¥add {対象者のid}
対象者をlistに追加する

## 追加した対象者一覧を確認するコマンド
- ¥コマンド名
addコマンドで追加したユーザーの名前が一覧として表示される
コマンド名思い付きませんでした😥

## 対象者に処理を実行するコマンド
- ¥run
作業項目に書かれている処理を実行します。

## 対象者一覧をリセットするコマンド
- ¥reset

## 対象者一覧から一人だけ取り消すコマンド
- ¥remove {対象者一覧に入ってるユーザーのid}
対象者一覧に入っているユーザーをIDを指定する事によって、一人ずつ取り消す事ができます。

**Comment by iceE-1591** [comment]
## 必要なコマンドを説明付きで書いてみました

### 対象者を追加するコマンド
- ¥add {対象者のid}
対象者をlistに追加する

### 追加した対象者一覧を確認するコマンド
- ¥コマンド名
addコマンドで追加したユーザーの名前が一覧として表示される
コマンド名思い付きませんでした😥

### 対象者に処理を実行するコマンド
- ¥run
作業項目に書かれている処理を実行します。

### 対象者一覧をリセットするコマンド
- ¥reset

### 対象者一覧から一人だけ取り消すコマンド
- ¥remove {対象者一覧に入ってるユーザーのid}
対象者一覧に入っているユーザーをIDを指定する事によって、一人ずつ取り消す事ができます。

**Comment by su-pleiades** [comment]
追加した対象者一覧を確認するコマンド
- targets

でいきましょ！

**Comment by su-pleiades** [comment]
- ¥kick {いっちーさんが上記で指定したコマンドたち}
¥kickをコマンド名にして、サブコマンドに「add/remove/targets/run/reset/remove」を入れていきましょう

**Comment by iceE-1591** [comment]
## メインコマンド
- kick
## サブコマンド
- add
- targets
- run
- reset
- remove

**Comment by iceE-1591** [comment]
すーさんだけ実行可能にすれば大丈夫ですか？
SubAdminの方も使う可能性はありますか？

**Comment by iceE-1591** [comment]
対象者一覧を確認するコマンドを`targets`から`list`に変更しました。

**Comment by iceE-1591** [comment]
groupデコレータを採用しました。
