### ISSUE TITLE
「もくもく勉強机{n}」が全て埋まった時自動でVCを作成する機能

### ISSUE THREAD

**Issue by su-pleiades** [mo9mo9study/discord.CodeWarehouse#61]
# 経緯
- もくもく勉強机が全て埋まった際に、管理者がその都度手動で作成していた
- アップデート情報に以下の文字列を送信していた
  - [・ボイスチャンネル「もくもく勉強机14」を作成しました]
  
# 機能
- 「もくもく勉強机」の全てのVCに人が入室している（全て埋まっている）時、後続の数字で勉強机を自動作成する
- VCを作成したことをチャンネルメッセージで送信して知らせる機能

**Comment by iceE-1591** [comment]
僕が想定しているものは `勉強机作成用` の様なvcチャンネルを1つ作って、そこに入ると新しくvcが作成され、抜けると作成されたvcチャンネルが消えるようなものです。

現在14つの勉強机が用意されていますがこれらすべてを削除することによって、他のチャンネルに行きやすくなりますし全てのチャンネルが満室になっても自分で作成できるので、管理者の負担もなくなり勉強したい人もスムーズにできるようになると思いました。

**Comment by nntsugu** [comment]
- 勉強机の最小数について
  - 机の残数が1しかない場合、遠慮して机に入らない人もいると思うので最小2-3個以上の空き勉強机を置いておけると良いんじゃないかと思います
  - 余談ですが何人かの方はお気に入りの机番号があるようです。が、そこはすぐ慣れるだろうし気にしないでいいかもしれません（正直何が正解かわからん）

**Comment by su-pleiades** [comment]
あ、それでいうと
昔にいっちーさん同様に同じ機能作ったけど、
nntsuguさんのいう通り歴史あって
自動作成される仕組みは没にしたんだよね。

余裕を持たせるなら、
- メンバーがVC参加時に
  - 「もくもく勉強机総数」を計算
  - 「もくもく勉強机が埋まってる数」を計算
  - 「（「もくもく勉強机総数」を計算） - ( 「もくもく勉強机が埋まってる数」を計算 ) = 1」になった時新規VC作成（空き計算）
  
  かな？

**Comment by iceE-1591** [comment]
> 
> 
> あ、それでいうと
> 昔にいっちーさん同様に同じ機能作ったけど、
> nntsuguさんのいう通り歴史あって
> 自動作成される仕組みは没にしたんだよね。
> 
> 余裕を持たせるなら、
> 
>     * メンバーがVC参加時に
>       
>       * 「もくもく勉強机総数」を計算
>       * 「もくもく勉強机が埋まってる数」を計算
>       * 「（「もくもく勉強机総数」を計算） - ( 「もくもく勉強机が埋まってる数」を計算 ) = 1」になった時新規VC作成（空き計算）
>       
>       かな？

なるほど。
分かりました

新規作成したvcは削除せずにそのまま残して増やしていく感じですか？

**Comment by iceE-1591** [comment]
https://github.com/mo9mo9study/discord.CodeWarehouse/pull/62
テストして頂けたら幸いです。
不具合などありましたら連絡ください

**Comment by su-pleiades** [comment]
今回の処理のIDってうちのギルドIDと「STUDY SPACE」カテゴリーのIDに変更してよいの？？
- コードの中でon_readyがあるのはなんでだっけ。
  - というのを @iceE-1591 に確認
# リポジトリ
- https://github.com/mo9mo9study/discord.CodeWarehouse/tree/revert-65-revert-62-add/createStudyDesk

**Comment by iceE-1591** [comment]
- IDに関してはそれに変更して下さい！
## 何故、on_readyイベントがあるのか
- __init__メソッド内で格納したIDをGUILDオブジェクトとCATEGORYオブジェクトにする為です。
on_ready内でオブジェクトにしてしまえば、on_voice_state_updateイベント内の処理が走った時に、毎回CATEGORYをgetしなくて済むためです。

**Comment by su-pleiades** [comment]
#71 で後続の問題発生
