### ISSUE TITLE
タイマー機能を追加

### ISSUE THREAD

**Issue by tako-eng** [mo9mo9study/discord.CodeWarehouse#63]
### 経緯
勉強道場で、切り上げる時間になっても気づかなかったので、
気づける機能がほしいなと思っています。

### 機能
・コマンド投稿したチャンネルに、設定した時間になったら時間がきたことを知らせてくれる
・経過時間でなくて、時間そのものをセットできたらうれしい（8:00にセットしたかったら、!reminder 0800」みたいな）。
・日を跨いで使うことはまずなさそうなので、日付指定は不要でhh:mmだけでよいかなと思っています。

### 例
!reminder 0800
[bot]08:00にお知らせするよう設定しました！

時間がきたら
[bot]時間です！お疲れ様でした。

みたいなもの。（時間がきたことがわかれば、メッセージはなんでもいいです）
いまは勉強道場で使うことを想像しています。

### 参考までに...
他のdiscordで同じ機能をみたときの投稿は
[bot]7:00 になりました。もくもくタイムです
[bot]8:00 になりました。もくもくタイムは終了です。お疲れさまでした。
みたいな感じでした。

**Comment by iceE-1591** [comment]
良い機能ですね👍
- !reminder 終了時間
その時刻に通知する

- !reminder 開始時間 終了時間
参考と同じ機能

時間があるので、上記の機能を作ってみます。

**Comment by tako-eng** [comment]
プラスアルファまで、ありがとうございます😸
よろしくおねがいします。

**Comment by iceE-1591** [comment]
コマンド名がreminderですが、長くて不便だと思うので何か案があれば！
- re
- rem

**Comment by tako-eng** [comment]
あ、rem手短でわかりやすくていいですね！
remに1票、おねがいします😸

**Comment by iceE-1591** [comment]
勉強道場のボイスチャットは1つしかないので、2つ以上のReminderを同時に設定する事は視野に入れずに開発していいですか?

**Comment by tako-eng** [comment]
はい！
現状、2つ以上のReminderを同時に設定する事はいまはなさそうなので、1つでじゅうぶんです😸

**Comment by iceE-1591** [comment]
分かりました👌

**Comment by su-pleiades** [comment]
通知先について @tako-eng さんに確認
- 通知専用チャンネル作るべきか、
- それとも既存のチャンネル「道場_チャット」とかでいいのか

**Comment by iceE-1591** [comment]
> 通知先について @tako-eng さんに確認
> 
> - 通知専用チャンネル作るべきか、
> 
> - それとも既存のチャンネル「道場_チャット」とかでいいのか

今現在は、既存のチャンネルでいいとのこと
- [+α]コマンド入力をした所に通知する

**Comment by iceE-1591** [comment]
公開Bot導入によって、一時開発の中断

**Comment by su-pleiades** [comment]
- 一旦reminder-bot導入にて対応済み
https://reminder-bot.com/help/
