### ISSUE TITLE
[機能提案]勉強中の言語・取得済み言語を可視化させる

### ISSUE THREAD

**Issue by iceE-1591** [mo9mo9study/discord.CodeWarehouse#70]
## 問題
- プログラミング関連で質問したい時に、例えば「PHPをやってる方に質問で~~」の様に書かないと誰に質問しているのか、誰が答えていいのかがわかりません。
そんな時にプログラミング言語名と同じ名前のroleがあれば、そのroleにメンションするだけで質問の対象者が誰なのかが分かりやすいですし、通知も行くのでレスポンスが早くなっていい環境になると思いました。

## 提案内容
- プログラミング言語名と同じ名前のroleをサーバーに追加
(1サーバーのRole数上限は250, 現在のmo9mo9サーバーrole数は48、空きに余裕があるので提案してみました)
- 現在のRssの様にリアクションを押すことで、自分の学んでいる言語や習得済み言語の名前のroleがつくようになる
- 対応リアクション用の絵文字に関しては、Discord内の外部サーバーを作成しそこにプログラミング言語名のEmojiを作成
(BotはNitro判定になるので、Botがサーバーに入っていればemojiを上限なく絵文字を追加できる)

### メリット
- 「この方は何の言語を使っているんだろう？」といった場合に、メンバーをタップするだけでroleを見ればどの言語を習得しているかが簡単に分かる
- 特定の言語で詰まった時に「@プログラミング言語名」の様にメンションすれば、そのroleを付けている人に通知が行き、問題解決が早まる
### デメリット
- 新しい機能というのもありますが、数人しか使ってくれないとあまり意味がない
- role一覧が汚れる可能性がある

## 気になることがあったら気軽にコメント下さい

**Comment by iceE-1591** [comment]
絵文字は `kashi` さんが作成に協力してくれます。

**Comment by su-pleiades** [comment]
よき！

**Comment by iceE-1591** [comment]
- 主な処理はRssのコードを使いまわす
- 設定ファイルにはyamlファイルを採用
- 絵文字は各言語のシンボルを採用

**Comment by iceE-1591** [comment]
C
C#
C++
Go
Java
JavaScript
Kotlin
Objective-C
PHP
Python
Ruby
Scala
Swift
TypeScript

初期案

**Comment by iceE-1591** [comment]
## 初期案
- C
- C#
- C++
- Go
- Java
- JavaScript
- Kotlin
- Objective-C
- PHP
- Python
- Ruby
- Scala
- Swift
- TypeScript

**Comment by iceE-1591** [comment]
## 追加
- HTML
- CSS
- SQL
- VBA

**Comment by iceE-1591** [comment]
## 決定
- C
- C#
- C++
- Go
- Java
- JavaScript
- Kotlin
- Objective-C
- PHP
- Python
- Ruby
- Scala
- Swift
- TypeScript
- HTML
- CSS
- SQL
- VBA
- node.js

**Comment by su-pleiades** [comment]
# ロールを作る処理
- ロール名カラー：ダークイエロー
- 権限なし
- メンション許可
# 動くことのみ確認・実行済み（一時的な処理のメモ）
```
@bot.command()
async def createroles(ctx, *args):
    print(f"type of args: {type(args)}")
    hexcolour="CC7900"
    for rolename in args:
        await ctx.guild.create_role(
            name=rolename, 
            mentionable=True, 
            colour=discord.Colour(int(hexcolour, 16)),
            permissions=discord.Permissions(permissions=0)
        )
        await ctx.channel.send(f"「@{rolename} 」というロールを作成しました")

bot.run(TOKEN)
```

**Comment by su-pleiades** [comment]
これら取得したロールの情報をどこかで確認できるダッシュボードみたいな物を作る？

- （１）言語ごとに付与されている人を表示するパターン
```
[ Python ]
SuPleiades / いっちー / kashi
[ Javascript ]
SuPleiades
```
- （２）人ごとに付与されている言語のroleを表示するパターン
```
[ SuPleiades ]
Python / Javascript
[ いっちー ] 
Python
[ kashi ]
Python
```
