### ISSUE TITLE
寝落ち対策用のBOT機能開発

### ISSUE THREAD

**Issue by su-pleiades** [mo9mo9study/discord.CodeWarehouse#8]
# 開発メンバー募集
- 興味ある方は自らアサインお願いします
- 権限関係リポジトリ管理者把握してないので、アサイン出来なければコメントお願いします

# 目的
- ボイスチャットに参加したまま寝落ちした人
-「寝言・いびき聞かれてないか？！」と不安にならないような機能

# イメージ
- 「この人寝落ちしてるな」と気づいた人がそっとその人をマイクミュートしたり、チャンネル移動できる機能
- コマンド
  - 例）¥mmv {member_ID}
  - 上記コマンドを打ったらその人がマイクミュートされたり、AFKチャンネルに移動させられる

# 条件
- AFK botを導入
- 同じボイチャにいる人同士だけがAFK botを使用できる
- AFK botは対象がマイクミュートだった場合移動しない
- 作業部屋とラウンジ以外ではAFK bot実行用ロールを付与しない
  - 勉強中の人を強引に移動させる事故がおきにくくする

※上記条件は確定ではなく、仮の状態であり、細かい条件は作り手によるものとする
※上記条件以外で案あれば是非このissueで共有ください

**Comment by su-pleiades** [comment]
# 追加条件
- 「¥mmv @{メンション}」で実行できるようにする

**Comment by iceE-1591** [comment]
# 追加条件
- 対象ユーザーのtimesチャンネルに通知を飛ばす様にする

**Comment by iceE-1591** [comment]
## エラーを修正
- メンションからidを取得するスライスの値を変更
- 要らなくなったif文を削除
