### ISSUE TITLE
基本コマンドのaliasについて

### ISSUE THREAD

**Issue by iceE-1591** [mo9mo9study/discord.CodeWarehouse#85]
## 現状
今現在、勉強時間を確認するコマンドは `¥result_d` となっています。
なので `¥rd ago` の様に実行できると、便利だと思いました。

## 提案
`¥result_d` などの現在存在しているコマンドは今まで通り残し、`¥rd`を追加

**Comment by supleiades** [comment]
コマンドを基本的に使わない方針で進めているためクローズ
コマンドでなく、リアクションで操作するUI
![image](https://user-images.githubusercontent.com/45380191/133956448-b82623bb-1fa2-432f-99e6-0128ac3793a4.png)
