### ISSUE TITLE
自己紹介送信前にBOTを再起動させると正常に送信処理がされない問題

### ISSUE THREAD

**Issue by supleiades** [mo9mo9study/discord.CodeWarehouse#96]
# 予想される原因
- 自己紹介メッセージ送信前の処理でBOTを停止させるとBOTは起動前のメッセージにスタンプが付与されようがトリガーとしての機能を失うため、内部をしならないユーザー視点では現状送信できなくなってしまう

# 解決策
- 全てのパラメータが登録されている状態で、BOTの再起動が行われた際は改めて「確認のメッセージ」を送信するようにする
![image](https://user-images.githubusercontent.com/45380191/116116819-8779bc80-a6f6-11eb-8f65-7a14521935ef.png)

**Comment by su-pleiades** [comment]
BOT起動前
![image](https://user-images.githubusercontent.com/45380191/116643501-2c70ef80-a9ac-11eb-8ca5-6c66499d7f8d.png)
BOT起動後
![image](https://user-images.githubusercontent.com/45380191/116643476-20852d80-a9ac-11eb-8214-6d7f9d943e07.png)
![image](https://user-images.githubusercontent.com/45380191/116643518-34c92a80-a9ac-11eb-8aeb-1af8a1ac4422.png)

正常に動いてるようだ
もちろんチャンネルも作成された
